export const UP = 'UP'
export const DOWN = 'DOWN'
export const RIGHT = 'RIGHT'
export const LEFT = 'LEFT'

export const RIGHT_INTER = 'RIGHT-INTER'
export const LEFT_INTER = 'LEFT-INTER'
export const DOWN_INTER = 'DOWN-INTER'

export const LEFT_UP = 'LEFT_UP'
export const LEFT_DOWN = 'LEFT_DOWN'
export const RIGHT_UP = 'RIGHT_UP'
export const RIGHT_DOWN = 'RIGHT_DOWN'

export const ANGLE_VERT = 'ANGLE_VERT'
export const ANGLE_HORI = 'ANGLE_HORI'

// export const TOP = 'TOP'
// export const BOTTOM = 'BOTTOM'


export const TOPIC = 'TOPIC'
export const BRANCH = 'BRANCH'
export const GROUP = 'GROUP'
export const BOUNDARY = 'BOUNDARY'
export const CONN = 'CONN'

export const MAP = 'MAP'
export const ORG = 'ORG'
export const ORG_UP = 'ORG_UP'
export const LOGIC_R = 'LOGIC_R'
export const LOGIC_L = 'LOGIC_L'
export const TREE_L = 'TREE_L'
export const TREE_R = 'TREE_R'
export const TIME_UP = 'TIME_UP'
export const TIME_DOWN = 'TIME_DOWN'
export const TIME_H_UP = 'TIME_H_UP'
export const TIME_H_DOWN = 'TIME_H_DOWN'
export const TIME_H = 'TIME_H'
export const TIME_V = 'TIME_V'

export const FISH_RIGHT_UP_IN = 'FISH_RIGHT_UP_IN'
export const FISH_RIGHT_DOWN_IN = 'FISH_RIGHT_DOWN_IN'
export const FISH_LEFT_UP_IN = 'FISH_LEFT_UP_IN'
export const FISH_LEFT_DOWN_IN = 'FISH_LEFT_DOWN_IN'
export const FISH_RIGHT_UP = 'FISH_RIGHT_UP'
export const FISH_RIGHT_DOWN = 'FISH_RIGHT_DOWN'
export const FISH_LEFT_UP = 'FISH_LEFT_UP'
export const FISH_LEFT_DOWN = 'FISH_LEFT_DOWN'
export const FISH_RIGHT = 'FISH_RIGHT'
export const FISH_LEFT = 'FISH_LEFT'
